name: Build EXE

on:
  push:
    paths:
      - '**.py'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PyInstaller + pyperclip
        run: |
          pip install pyinstaller pyperclip
          pyinstaller --onefile --windowed faceless_ui_20250805_192309.py

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FacelessEXE
          path: dist/faceless_ui_20250805_192309.exe
          retention-days: 1
# trigger build
